name: Archive Video to IA

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'video URL to archive'
        required: true
        default: 'https://youtu.be/dQw4w9WgXcQ'

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache pip & yt-dlp
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/yt-dlp
        key: ${{ runner.os }}-archive-cache-${{ hashFiles('.github/workflows/tubeup.yml') }}
        restore-keys: |
          ${{ runner.os }}-archive-cache-

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install tubeup and IA CLI
      run: |
        python -m pip install --upgrade pip
        pip install tubeup internetarchive

    - name: Configure IA CLI
      env:
        IA_EMAIL: ${{ secrets.IA_EMAIL }}
        IA_PASSWORD: ${{ secrets.IA_PASSWORD }}
      run: |
        printf "%s\n%s\n" "$IA_EMAIL" "$IA_PASSWORD" | ia configure

    - name: Run tubeup
      run: |
        tubeup "${{ github.event.inputs.url }}"
